name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        cuda_ver: ['11.2.2', '11.2.2']
    if: "!contains(github.event.head_commit.message, '[ci skip]')"  # respect [ci skip] commit
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.1
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda_ver }}
          method: network
          subPackages: '["nvcc"]'
      - name: setup msvc
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./build.bat
      - name: Build wheels
        run: |
          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V
          cl --version
          pip install numpy cython wheel
          python setup.py develop
          python setup.py sdist bdist_wheel
